import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import http from 'node:http';
import { createFixture } from './test-fixture.mjs';

test('local console persists decisions, rejects stale views and blocks unapproved application', async (t) => {
  const fixture = await createFixture(); t.after(fixture.cleanup);
  fixture.execute('review', 'fixture');
  const { createConsole } = await import(pathToFileURL(path.join(fixture.tool, 'console.mjs')));
  const app = await createConsole({ port: 0 }); t.after(() => new Promise((resolve) => app.server.close(resolve)));
  const session = await (await fetch(`${app.url}/api/session`)).json();
  const post = (url, body, headers = {}) => fetch(`${app.url}${url}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Console-Token': session.token, ...headers }, body: JSON.stringify(body) });
  const badHostStatus = await new Promise((resolve, reject) => {
    http.get(`${app.url}/api/session`, { headers: { Host: 'evil.example' } }, (response) => { response.resume(); resolve(response.statusCode); }).on('error', reject);
  });
  assert.equal(badHostStatus, 403);
  assert.equal((await post('/api/jobs', { action: 'check' }, { Origin: 'https://evil.example' })).status, 403);
  assert.equal((await post('/api/jobs', { action: 'check' }, { 'X-Console-Token': 'wrong' })).status, 403);
  const index = await (await fetch(`${app.url}/api/runs`)).json(); assert.equal(index.runs[0].status, 'reviewable');
  const model = await (await fetch(`${app.url}/api/runs/fixture`)).json();
  assert.equal(model.summary.pending, 1);
  const source = await (await fetch(`${app.url}/api/runs/fixture/source?file=fixture.json`)).json();
  assert.deepEqual(source.body, {});
  assert.equal((await fetch(`${app.url}/api/runs/fixture/source?file=../../corrections.json`)).status, 409);
  assert.equal((await post('/api/jobs', { action: 'apply', run: 'fixture', report_hash: model.report_hash })).status, 409);
  const change = { report_hash: model.report_hash, revision: 0, changes: [{ id: model.items[0].id, status: 'keep', note: 'Keep existing wording until verified' }] };
  assert.equal((await post('/api/runs/fixture/decisions', change)).status, 200);
  assert.equal((await post('/api/runs/fixture/decisions', change)).status, 409);
  let saved = await (await fetch(`${app.url}/api/runs/fixture`)).json(); assert.equal(saved.summary.held, 1);
  assert.equal((await post('/api/jobs', { action: 'apply', run: 'fixture', report_hash: model.report_hash })).status, 409);
  change.revision = 1; change.changes[0].status = 'accepted';
  assert.equal((await post('/api/runs/fixture/decisions', change)).status, 200);
  saved = await (await fetch(`${app.url}/api/runs/fixture`)).json(); assert.equal(saved.summary.ready, true);
  const exported = await (await fetch(`${app.url}/api/runs/fixture/export`)).json();
  assert.equal(exported.decisions.history.length, 2);
  fixture.execute('review', 'fixture');
  const reviewed = await (await fetch(`${app.url}/api/runs/fixture`)).json();
  assert.equal(reviewed.summary.pending, 1);
  assert.equal(reviewed.summary.ready, false);
  const reset = await (await fetch(`${app.url}/api/runs/fixture/export`)).json();
  assert.equal(reset.decisions.history.length, 2);
  const reportFile = path.join(fixture.run, 'review.json'); const before = await fs.readFile(reportFile); await fs.appendFile(reportFile, '\n');
  assert.equal((await post('/api/runs/fixture/decisions', { ...change, revision: 2 })).status, 409);
  await fs.writeFile(reportFile, before);
  await fs.appendFile(fixture.translationFile, '\n');
  assert.equal((await post('/api/jobs', { action: 'apply', run: 'fixture', report_hash: model.report_hash })).status, 409);
});
