import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from '@playwright/test';
import { createFixture } from './test-fixture.mjs';

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test(`published data supports filtering, complete details and refresh at ${viewport.width}px`, { timeout: 60000 }, async (t) => {
    const fixture = await createFixture(); t.after(fixture.cleanup); fixture.execute('review', 'fixture');
    const { createConsole } = await import(pathToFileURL(path.join(fixture.tool, 'console.mjs')));
    const app = await createConsole({ port: 0 }); t.after(() => new Promise((resolve) => app.server.close(resolve)));
    const browser = await chromium.launch({ headless: true }); t.after(() => browser.close());
    const page = await browser.newPage({ viewport }); const errors = []; page.on('pageerror', (error) => errors.push(error.message));
    await page.route('https://raw.githubusercontent.com/**', (route) => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" />' }));
    await page.goto(`${app.url}/#data`);
    await page.locator('#data-result-count').filter({ hasText: '1135 / 1135' }).waitFor();
    assert.equal(await page.locator('#workspace').isVisible(), false);
    assert.equal(await page.locator('.data-record').count(), 30);
    await page.locator('#data-next').click();
    await page.locator('#data-page-label').filter({ hasText: '2 /' }).waitFor();
    await page.getByRole('searchbox', { name: '搜索当前数据' }).fill('#0001');
    await page.locator('#data-result-count').filter({ hasText: '1 / 1135' }).waitFor();
    await page.getByRole('button', { name: '查看 妙蛙种子', exact: true }).click();
    const detail = page.locator('#data-detail');
    await detail.getByText('六项种族值', { exact: true }).waitFor();
    await detail.getByText('Bulbasaur', { exact: true }).first().waitFor();
    await detail.getByText('查看原始 JSON', { exact: true }).click();
    assert.match(await detail.locator('pre').textContent(), /"base_stats_total": 318/);
    await page.getByRole('button', { name: '关闭数据详情' }).click();
    await page.getByRole('searchbox', { name: '搜索当前数据' }).fill('フシギダネ');
    await page.getByLabel('世代', { exact: true }).selectOption('1');
    await page.getByLabel('属性', { exact: true }).selectOption('grass');
    await page.getByLabel('标签', { exact: true }).selectOption('starter');
    await page.locator('#data-result-count').filter({ hasText: '1 / 1135' }).waitFor();
    await page.getByLabel('世代', { exact: true }).selectOption('9');
    await page.getByText('没有符合条件的数据。可以更换关键词或清除筛选。').waitFor();
    await page.getByRole('button', { name: '清除筛选' }).click();
    await page.getByRole('button', { name: '多语言名称', exact: true }).click();
    await page.getByLabel('名称类别').selectOption('ability');
    await page.getByRole('searchbox', { name: '搜索当前数据' }).fill('overgrow');
    await page.locator('.data-record').first().click();
    await detail.getByText('Overgrow', { exact: true }).waitFor();
    await page.getByRole('button', { name: '关闭数据详情' }).click();
    await page.getByRole('button', { name: '恶作剧图片', exact: true }).click();
    await page.locator('#data-result-count').filter({ hasText: '19 / 19' }).waitFor();
    await page.getByRole('button', { name: '知识文章索引', exact: true }).click();
    await page.locator('.data-record').first().click();
    await detail.getByText('关联语言', { exact: true }).waitFor();
    await page.getByRole('button', { name: '关闭数据详情' }).click();
    const index = await (await fetch(`${app.url}/api/runs/fixture`)).json();
    await page.locator('#runs button').first().click();
    await page.locator('.item-name button').first().click();
    await page.getByRole('button', { name: '接受变更', exact: true }).click();
    await page.locator('#detail').waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: '当前数据 浏览全部已发布数据' }).click();
    fixture.execute('apply', 'fixture', '--review', index.report_hash);
    await page.getByRole('button', { name: '刷新数据', exact: true }).click();
    await page.getByRole('button', { name: '宝可梦', exact: true }).click();
    await page.getByLabel('显示语言').selectOption('en');
    await page.getByRole('searchbox', { name: '搜索当前数据' }).fill('Updated fixture name');
    await page.getByRole('button', { name: '查看 Updated fixture name', exact: true }).waitFor();
    let release; let started;
    const delayed = new Promise((resolve) => { release = resolve; });
    const requested = new Promise((resolve) => { started = resolve; });
    const delayedRoute = async (route) => { started(); await delayed; await route.continue(); };
    await page.route('**/api/runs/fixture', delayedRoute);
    await page.locator('#runs button').first().click(); await requested;
    await page.getByRole('button', { name: '当前数据 浏览全部已发布数据' }).click();
    const response = page.waitForResponse('**/api/runs/fixture'); release(); await response;
    await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert.equal(await page.locator('#current-data').isVisible(), true);
    assert.equal(new URL(page.url()).hash, '#data');
    await page.unroute('**/api/runs/fixture', delayedRoute);
    await page.reload();
    await page.locator('#data-result-count').filter({ hasText: '1135 / 1135' }).waitFor();
    assert.equal(await page.locator('#workspace').isVisible(), false);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    assert.deepEqual(errors, []);
  });

  test(`console decisions survive reload and gate application at ${viewport.width}px`, { timeout: 60000 }, async (t) => {
    const fixture = await createFixture(); t.after(fixture.cleanup); fixture.execute('review', 'fixture');
    const { createConsole } = await import(pathToFileURL(path.join(fixture.tool, 'console.mjs')));
    const app = await createConsole({ port: 0 }); t.after(() => new Promise((resolve) => app.server.close(resolve)));
    const browser = await chromium.launch({ headless: true }); t.after(() => browser.close());
    const page = await browser.newPage({ viewport }); const errors = []; page.on('pageerror', (error) => errors.push(error.message));
    await page.goto(app.url);
    await page.getByText('Updated fixture name', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '应用并运行检查' }).isDisabled(), true);
    await page.locator('.item-name button').first().click();
    await page.getByRole('button', { name: '查看缓存证据' }).click();
    await page.locator('#source-body').filter({ hasText: 'pokemon-species/1/' }).waitFor();
    await page.getByLabel('审核备注').fill('需要重新校对名称');
    await page.getByRole('button', { name: '要求修正', exact: true }).click();
    await page.locator('#detail').waitFor({ state: 'hidden' });
    await page.reload();
    await page.locator('#count-held').filter({ hasText: '1' }).waitFor();
    assert.equal(await page.getByRole('button', { name: '应用并运行检查' }).isDisabled(), true);
    await page.locator('.item-name button').first().click();
    assert.equal(await page.getByLabel('审核备注').inputValue(), '需要重新校对名称');
    await page.getByRole('button', { name: '接受变更', exact: true }).click();
    await page.locator('#detail').waitFor({ state: 'hidden' });
    await page.waitForFunction(() => !document.getElementById('apply').disabled);
    await page.reload(); await page.waitForFunction(() => !document.getElementById('apply').disabled);
    const review = await (await fetch(`${app.url}/api/runs/fixture`)).json();
    fixture.execute('apply', 'fixture', '--review', review.report_hash);
    await page.reload();
    await page.locator('#run-status').filter({ hasText: '已应用' }).waitFor();
    assert.equal(await page.getByRole('button', { name: '应用并运行检查' }).isDisabled(), true);
    await page.locator('.item-name button').first().click();
    assert.equal(await page.getByLabel('审核备注').isVisible(), false);
    assert.match(await page.locator('#saved-decision').textContent(), /需要重新校对名称/);
    const exported = await (await fetch(`${app.url}/api/runs/fixture/export`)).json();
    await fs.mkdir(path.join(fixture.tool, 'reports'));
    await fs.writeFile(path.join(fixture.tool, 'reports/2026-09-12.json'), JSON.stringify(exported));
    await fs.rm(fixture.run, { recursive: true });
    await page.reload();
    await page.locator('#run-status').filter({ hasText: '已应用' }).waitFor();
    assert.equal(await page.getByRole('button', { name: '从缓存重建', exact: true }).isDisabled(), true);
    await page.locator('.item-name button').first().click();
    assert.match(await page.locator('#saved-decision').textContent(), /需要重新校对名称/);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    assert.deepEqual(errors, []);
  });
}

for (const width of [1440, 390]) {
  test(`review navigation saves one item at a time and protects unsaved notes at ${width}px`, { timeout: 60000 }, async (t) => {
    const fixture = await createFixture(); t.after(fixture.cleanup);
    const translations = JSON.parse(await fs.readFile(fixture.translationFile));
    translations.ivysaur.en = 'Second fixture name';
    await fs.writeFile(fixture.translationFile, JSON.stringify(translations));
    fixture.manifest.candidate['pokemon_i18n.json'] = await fixture.fileHash(fixture.translationFile);
    await fs.writeFile(path.join(fixture.run, 'manifest.json'), JSON.stringify(fixture.manifest));
    fixture.execute('review', 'fixture');
    const { createConsole } = await import(pathToFileURL(path.join(fixture.tool, 'console.mjs')));
    const app = await createConsole({ port: 0 }); t.after(() => new Promise((resolve) => app.server.close(resolve)));
    const browser = await chromium.launch({ headless: true }); t.after(() => browser.close());
    const page = await browser.newPage({ viewport: { width, height: 900 } });
    await page.route('https://raw.githubusercontent.com/**', (route) => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg"/>' }));
    await page.goto(app.url);
    await page.locator('.item-name button').first().click();
    const title = await page.locator('#detail-title').textContent();
    await page.getByLabel('审核备注').fill('已核对名称');
    await page.getByRole('button', { name: '下一项待确认' }).click();
    await page.getByText('备注尚未保存，请先保存审核决定再切换。').first().waitFor();
    assert.equal(await page.locator('#detail-title').textContent(), title);
    await page.getByRole('button', { name: '接受并下一项' }).click();
    await page.waitForFunction((title) => document.getElementById('detail-title').textContent !== title, title);
    await page.locator('#review-progress-label').filter({ hasText: '1 / 2' }).waitFor();
    await page.getByRole('button', { name: '接受变更', exact: true }).click();
    await page.locator('#review-progress-label').filter({ hasText: '2 / 2' }).waitFor();
    const decisions = JSON.parse(await fs.readFile(path.join(fixture.run, 'decisions.json')));
    assert.equal(Object.keys(decisions.decisions).length, 2);
    assert(Object.values(decisions.decisions).some((decision) => decision.note === '已核对名称'));
    const font = await fetch(`${app.url}/fonts/inter-latin-variable.woff2`);
    assert.equal(font.headers.get('content-type'), 'font/woff2');
    assert.equal(Buffer.from(await font.arrayBuffer()).subarray(0, 4).toString(), 'wOF2');
  });
}
