import * as fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { paths } from './pipeline.mjs';
import { inspectMdx, syncArticleMetadata } from './knowledge-mdx.mjs';

export const knowledgeLocales = ['en', 'ja', 'zh-hans', 'zh-hant'];
const digest = (value) => createHash('sha256').update(value).digest('hex');
const json = (value) => `${JSON.stringify(value, null, 2)}\n`;
const key = (locale, slug) => `${locale}/${slug}`;
const normalize = (value) => value.normalize('NFC').toLowerCase();
const validSlug = (slug) => typeof slug === 'string' && slug.length <= 150 && /^[\p{L}\p{N}][\p{L}\p{N}\p{M} ._-]*$/u.test(slug) && slug === slug.trim() && !slug.endsWith('.mdx');
const optional = async (file) => { try { return await fs.readFile(file, 'utf8'); } catch (error) { if (error.code === 'ENOENT') return null; throw error; } };

export function registrySource(index) {
  const entries = knowledgeLocales.flatMap((locale) => index[locale].map(({ slug }) => `  ${JSON.stringify(key(locale, slug))}: () => import(${JSON.stringify(`./knowledge/${locale}/${slug}.mdx`)}),`));
  return `// Generated by the knowledge console. Run mise run knowledge:sync after manual index edits.\nimport type { ComponentType } from 'react';\n\nconst knowledgeLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {\n${entries.join('\n')}\n};\n\nexport default knowledgeLoaders;\n`;
}

export function createKnowledgeManager({ root = paths.root } = {}) {
  const data = path.join(root, 'src/data');
  const folder = path.join(data, 'knowledge');
  const indexFile = path.join(data, 'knowledge_data.json');
  const registryFile = path.join(data, 'knowledge-loaders.ts');
  let writing = false;
  async function safe(file) {
    const relative = path.relative(root, file);
    assert(!relative.startsWith('..') && !path.isAbsolute(relative), '文章路径越界');
    let current = root;
    for (const part of relative.split(path.sep)) {
      current = path.join(current, part);
      try { assert(!(await fs.lstat(current)).isSymbolicLink(), '知识库文件不能使用符号链接'); }
      catch (error) { if (error.code === 'ENOENT') break; throw error; }
    }
  }
  const sourceFile = (locale, slug) => {
    assert(knowledgeLocales.includes(locale), '知识库仅支持英语、日语、简体中文和繁体中文');
    assert(validSlug(slug), '路径名称只能包含文字、数字、空格、点、下划线和短横线，且不含 .mdx 后缀');
    return path.join(folder, locale, `${slug}.mdx`);
  };
  async function read() {
    await safe(indexFile); await safe(registryFile);
    const raw = await fs.readFile(indexFile, 'utf8');
    const index = JSON.parse(raw);
    const versions = new Map(); const identities = new Set(); const fileNames = new Set();
    const content = new Map([[indexFile, raw], [registryFile, await optional(registryFile)]]);
    for (const locale of knowledgeLocales) {
      assert(Array.isArray(index[locale]), `${locale} 文章索引无效`);
      for (const metadata of index[locale]) {
        assert(typeof metadata.id === 'string' && metadata.id && !identities.has(metadata.id), '文章版本 ID 缺失或重复');
        identities.add(metadata.id);
        assert(typeof metadata.title === 'string' && metadata.title.trim(), '文章标题缺失');
        assert(Number.isFinite(Date.parse(metadata.createdAt)), '文章创建时间无效');
        const file = sourceFile(locale, metadata.slug); await safe(file);
        assert(!fileNames.has(normalize(file)), `${locale} 的路径名称重复：${metadata.slug}`); fileNames.add(normalize(file));
        const source = await fs.readFile(file, 'utf8'); content.set(file, source);
        versions.set(key(locale, metadata.slug), { ...metadata, locale, source, file });
      }
    }
    const neighbors = new Map([...versions.keys()].map((id) => [id, new Set()]));
    for (const [id, version] of versions) {
      for (const [locale, reference] of Object.entries(version.translations ?? {})) {
        const target = key(locale, reference.slug);
        assert(versions.has(target), `语言关联不存在：${target}`);
        neighbors.get(id).add(target); neighbors.get(target).add(id);
      }
    }
    const visited = new Set(); const articles = [];
    for (const id of versions.keys()) {
      if (visited.has(id)) continue;
      const pending = [id]; const group = {};
      while (pending.length) {
        const current = pending.pop(); if (visited.has(current)) continue;
        visited.add(current); const version = versions.get(current);
        assert(!group[version.locale], '同一文章关联了两个相同语言的版本');
        group[version.locale] = version;
        pending.push(...neighbors.get(current));
      }
      const members = Object.values(group);
      const preferred = group['zh-hans'] ?? group.en ?? members[0];
      articles.push({ id: members.map((item) => item.id).sort()[0], title: preferred.title, versions: group });
    }
    return { index, articles, content, revision: digest([...content].sort(([a], [b]) => a.localeCompare(b)).map(([file, value]) => `${path.relative(root, file)}:${digest(value ?? '')}`).join('\n')) };
  }
  const publicModel = (snapshot) => ({
    revision: snapshot.revision, locales: knowledgeLocales,
    articles: snapshot.articles.map((article) => ({ ...article, versions: Object.fromEntries(Object.entries(article.versions).map(([locale, version]) => {
      const { file, ...fields } = version; return [locale, { ...fields, path: path.relative(root, file) }];
    })) })),
  });
  async function transaction(changes) {
    const originals = new Map(); const applied = [];
    const write = async (file, value) => {
      await safe(file); await fs.mkdir(path.dirname(file), { recursive: true });
      if (value === null) { await fs.rm(file, { force: true }); return; }
      const temporary = `${file}.tmp-${randomUUID()}`;
      try { await fs.writeFile(temporary, value, { flag: 'wx' }); await fs.rename(temporary, file); }
      finally { await fs.rm(temporary, { force: true }); }
    };
    for (const file of changes.keys()) { await safe(file); originals.set(file, await optional(file)); }
    try { for (const [file, value] of [...changes].sort(([, a], [, b]) => Number(a === null) - Number(b === null))) { await write(file, value); applied.push(file); } }
    catch (error) {
      const failures = [];
      for (const file of applied.reverse()) { try { await write(file, originals.get(file)); } catch (rollback) { failures.push(rollback.message); } }
      if (failures.length) throw new Error(`${error.message}；恢复失败：${failures.join('；')}`);
      throw error;
    }
  }
  async function update(body) {
    assert(!writing, '文章正在保存，请稍后重试'); writing = true;
    try {
      const before = await read();
      assert(body.revision === before.revision, '知识库已被其他窗口或文件编辑器修改。请先导出未保存内容，再重新载入后合并');
      assert(['save', 'deleteVersion', 'deleteArticle'].includes(body.action), '文章操作无效');
      let article = body.articleId ? before.articles.find((item) => item.id === body.articleId) : null;
      assert(!body.articleId || article, '文章已不存在，请重新载入');
      assert(body.action === 'save' || article, '请选择已有文章');
      if (!article) { article = { id: '', versions: {} }; before.articles.push(article); }
      const changes = new Map(); let savedID;
      if (body.action === 'save') {
        const version = body.version;
        assert(version && typeof version === 'object', '文章版本缺失');
        const locale = body.locale;
        const slug = typeof version.slug === 'string' ? version.slug.normalize('NFC') : version.slug;
        const file = sourceFile(locale, slug);
        assert(typeof version.title === 'string' && version.title.trim() && version.title.length <= 200, '标题不能为空，且不能超过 200 字符');
        assert(typeof version.createdAt === 'string' && Number.isFinite(Date.parse(version.createdAt)), '创建时间无效');
        const previous = article.versions[locale];
        for (const other of before.articles) for (const existing of Object.values(other.versions)) {
          assert(existing === previous || normalize(existing.file) !== normalize(file), `该语言已存在路径 ${slug}`);
        }
        await safe(file);
        if (!previous || previous.file !== file) assert(await optional(file) === null, '目标 MDX 文件已存在，不能覆盖未登记的文章');
        await inspectMdx(version.source);
        savedID = previous?.id ?? `k-${randomUUID()}`;
        const updatedAt = new Date().toISOString();
        const source = syncArticleMetadata(version.source, { locale, slug, title: version.title.trim(), createdAt: version.createdAt, updatedAt });
        await inspectMdx(source);
        article.versions[locale] = {
          id: savedID, title: version.title.trim(), slug, locale,
          createdAt: version.createdAt, updatedAt, source, file,
        };
        changes.set(file, source.endsWith('\n') ? source : `${source}\n`);
        if (previous && previous.file !== file) changes.set(previous.file, null);
      } else if (body.action === 'deleteVersion') {
        const version = article.versions[body.locale]; assert(version, '该语言版本不存在');
        changes.set(version.file, null); delete article.versions[body.locale];
        savedID = Object.values(article.versions)[0]?.id;
      } else {
        for (const version of Object.values(article.versions)) changes.set(version.file, null);
        article.versions = {};
      }
      const index = Object.fromEntries(knowledgeLocales.map((locale) => [locale, []]));
      for (const group of before.articles) {
        for (const [locale, version] of Object.entries(group.versions)) {
          const metadata = Object.fromEntries(Object.entries(version).filter(([name]) => !['file', 'source', 'locale', 'translations'].includes(name)));
          index[locale].push({ ...metadata, translations: Object.fromEntries(Object.entries(group.versions).filter(([other]) => other !== locale).map(([other, value]) => [other, { slug: value.slug }])) });
        }
      }
      changes.set(indexFile, json(index)); changes.set(registryFile, registrySource(index));
      assert((await read()).revision === body.revision, '保存期间文件已发生变化，请重新载入后合并');
      await transaction(changes);
      const after = await read();
      return { ...publicModel(after), selectedArticleId: after.articles.find((item) => Object.values(item.versions).some((version) => version.id === savedID))?.id ?? null };
    } finally { writing = false; }
  }
  async function check({ sync = false } = {}) {
    const snapshot = await read();
    for (const article of snapshot.articles) for (const version of Object.values(article.versions)) await inspectMdx(version.source);
    const expected = registrySource(snapshot.index);
    if (sync) await transaction(new Map([[registryFile, expected]]));
    else assert(snapshot.content.get(registryFile) === expected, '知识库加载清单过期，请运行 mise run knowledge:sync');
    return { articles: snapshot.articles.length, versions: Object.values(snapshot.index).reduce((count, list) => count + list.length, 0) };
  }
  return { list: async () => publicModel(await read()), update, check };
}

if (process.argv[1] && await fs.realpath(process.argv[1]) === import.meta.filename) {
  const action = process.argv[2]; assert(['check', 'sync'].includes(action), 'knowledge-model.mjs <check|sync>');
  const result = await createKnowledgeManager().check({ sync: action === 'sync' });
  console.log(`知识库${action === 'sync' ? '同步' : '校验'}通过：${result.articles} 篇文章，${result.versions} 个语言版本`);
}
