import { test } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import * as fs from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { chromium, expect } from '@playwright/test';
import { createFixture } from './test-fixture.mjs';

for (const width of [1440, 390]) {
  test(`knowledge editor manages MDX and language versions at ${width}px`, { timeout: 90000 }, async (t) => {
    const fixture = await createFixture(); t.after(fixture.cleanup);
    const { createConsole } = await import(pathToFileURL(path.join(fixture.tool, 'console.mjs')));
    const app = await createConsole({ port: 0 }); t.after(() => { app.server.closeAllConnections(); return new Promise((resolve) => app.server.close(resolve)); });
    const browser = await chromium.launch(); t.after(() => browser.close());
    const page = await browser.newPage({ viewport: { width, height: 1000 } });
    page.setDefaultTimeout(10000);
    const errors = []; page.on('pageerror', (error) => errors.push(error.message));
    await page.route('https://raw.githubusercontent.com/**', (route) => route.fulfill({ contentType: 'image/png', path: 'public/images/icon-96x96.png' }));
    await page.goto(`${app.url}/#knowledge`);
    await expect(page.locator('.knowledge-article-button')).toHaveCount(1);
    await expect(page.locator('#knowledge-title')).toHaveValue('示例文章');
    await page.getByRole('button', { name: '预览并校验', exact: true }).click();
    await expect(page.frameLocator('#knowledge-preview-frame').getByRole('heading', { level: 2 }).first()).toHaveText('示例文章');
    await page.getByRole('button', { name: '切换到夜间模式', exact: true }).click();
    await expect(page.frameLocator('#knowledge-preview-frame').locator('body')).toHaveCSS('background-color', 'rgb(27, 30, 36)');
    await expect(page.locator('.knowledge-editor-panel')).toHaveCSS('background-color', 'rgb(27, 30, 36)');
    await page.getByRole('button', { name: '切换到日间模式', exact: true }).click();
    await expect(page.frameLocator('#knowledge-preview-frame').locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
    await page.getByRole('button', { name: '编辑 MDX', exact: true }).click();
    await page.getByLabel('MDX 正文').fill('<Question>broken');
    await page.getByRole('button', { name: '预览并校验', exact: true }).click();
    await expect(page.locator('#notice')).toContainText('第 1 行');
    await expect(page.getByLabel('MDX 正文')).toHaveValue('<Question>broken');
    page.once('dialog', (dialog) => dialog.dismiss());
    await page.getByRole('button', { name: '新建文章', exact: true }).click();
    await expect(page.locator('#knowledge-title')).toHaveValue('示例文章');
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: '新建文章', exact: true }).click();
    await page.getByLabel('文章标题', { exact: true }).fill('测试新文章');
    await page.getByLabel('路径名称', { exact: true }).fill('new-article');
    await page.getByLabel('文章摘要', { exact: true }).fill('用于测试新文章的简体中文摘要。');
    await page.getByLabel('MDX 正文').fill('<Question>测试问题</Question>\n<Answer>\n**测试答案**\n</Answer>\n');
    await page.getByRole('button', { name: '保存到项目', exact: true }).click();
    await expect(page.locator('#notice')).toContainText('文章已保存到项目');
    await expect(page.locator('.knowledge-article-button')).toHaveCount(2);
    await page.locator('#knowledge-languages').getByRole('button', { name: '英语 ＋', exact: true }).click();
    await expect(page.getByLabel('路径名称', { exact: true })).toHaveValue('new-article');
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: '复制已有版本正文', exact: true }).click();
    await expect(page.getByLabel('MDX 正文')).toHaveValue(/测试问题/);
    await page.getByLabel('文章标题', { exact: true }).fill('New English article');
    await page.getByLabel('文章摘要', { exact: true }).fill('A guide to the test article.');
    await page.getByLabel('SEO 标题（可选）', { exact: true }).fill('Test article guide - Poke Wordle');
    await page.getByLabel('分享图片（可选）', { exact: true }).fill('/images/og-image.png');
    await expect(page.locator('#knowledge-search-title')).toHaveText('Test article guide - Poke Wordle');
    await page.getByLabel('MDX 正文').fill('## Question\n\n**Answer**\n');
    await page.getByRole('button', { name: '保存到项目', exact: true }).click();
    await expect(page.locator('#knowledge-dirty')).toHaveText('已保存到项目');
    const index = JSON.parse(await fs.readFile(path.join(fixture.data, 'knowledge_data.json')));
    assert.equal(index.en.find((item) => item.slug === 'new-article').translations['zh-hans'].slug, 'new-article');
    assert.equal(index.en.find((item) => item.slug === 'new-article').description, 'A guide to the test article.');
    await page.getByLabel('路径名称', { exact: true }).fill('new-article-v2');
    await page.getByRole('button', { name: '保存到项目', exact: true }).click();
    await expect(page.locator('#knowledge-dirty')).toHaveText('已保存到项目');
    await page.locator('#knowledge-redirects summary').click();
    await expect(page.locator('#knowledge-redirect-list')).toContainText('/knowledge/new-article');
    await page.getByLabel('MDX 正文').fill('## Unsaved version\n');
    page.once('dialog', (dialog) => dialog.dismiss());
    await page.getByRole('button', { name: '当前数据', exact: true }).click();
    await expect(page.locator('#knowledge-manager')).toBeVisible();
    await expect(page.getByLabel('MDX 正文')).toHaveValue('## Unsaved version\n');
    const download = page.waitForEvent('download'); await page.getByRole('button', { name: '导出 MDX', exact: true }).click();
    assert.equal((await download).suggestedFilename(), 'new-article-v2.en.mdx');
    await fs.appendFile(path.join(fixture.data, 'knowledge/en/new-article-v2.mdx'), '\nExternal edit\n');
    await page.getByRole('button', { name: '保存到项目', exact: true }).click();
    await expect(page.locator('#notice')).toContainText('其他窗口');
    await expect(page.getByLabel('MDX 正文')).toHaveValue('## Unsaved version\n');
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: '重新载入', exact: true }).click();
    await expect(page.getByLabel('MDX 正文')).toHaveValue(/External edit/);
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: '删除此语言版本', exact: true }).click();
    await expect(page.locator('#knowledge-title')).toHaveValue('测试新文章');
    await expect(page.locator('#knowledge-languages').getByRole('button', { name: '英语 ＋', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '预览并校验', exact: true }).click();
    await expect(page.frameLocator('#knowledge-preview-frame').getByRole('heading', { name: '测试问题' })).toBeVisible();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: `/private/tmp/poke-knowledge-console-${width}.png`, fullPage: true });
    page.once('dialog', (dialog) => dialog.accept());
    await page.getByRole('button', { name: '删除整篇文章', exact: true }).click();
    await expect(page.locator('.knowledge-article-button')).toHaveCount(1);
    await page.reload(); await expect(page.locator('#knowledge-title')).toHaveValue('示例文章');
    assert.deepEqual(errors, []);
  });
}
