// Generated by the knowledge console. Run mise run knowledge:sync after manual index edits.
import type { ComponentType } from 'react';

const knowledgeLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {
  "en/late-bloomers-pokemon": () => import("./knowledge/en/late-bloomers-pokemon.mdx"),
  "ja/大器晩成なポケモン": () => import("./knowledge/ja/大器晩成なポケモン.mdx"),
  "zh-hans/大器晚成的宝可梦": () => import("./knowledge/zh-hans/大器晚成的宝可梦.mdx"),
  "zh-hant/大器晚成的寶可夢": () => import("./knowledge/zh-hant/大器晚成的寶可夢.mdx"),
};

export default knowledgeLoaders;
