// Generated by the knowledge console. Run mise run knowledge:sync after manual index edits.
import type { ComponentType } from 'react';

const knowledgeLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {
  "en/late-bloomers-pokemon": () => import("./knowledge/en/late-bloomers-pokemon.mdx"),
  "en/guessing-clues": () => import("./knowledge/en/guessing-clues.mdx"),
  "en/generations-and-settings": () => import("./knowledge/en/generations-and-settings.mdx"),
  "en/forms-and-mega-evolution": () => import("./knowledge/en/forms-and-mega-evolution.mdx"),
  "ja/late-bloomers-pokemon": () => import("./knowledge/ja/late-bloomers-pokemon.mdx"),
  "ja/guessing-clues": () => import("./knowledge/ja/guessing-clues.mdx"),
  "ja/generations-and-settings": () => import("./knowledge/ja/generations-and-settings.mdx"),
  "ja/forms-and-mega-evolution": () => import("./knowledge/ja/forms-and-mega-evolution.mdx"),
  "zh-hans/late-bloomers-pokemon": () => import("./knowledge/zh-hans/late-bloomers-pokemon.mdx"),
  "zh-hans/guessing-clues": () => import("./knowledge/zh-hans/guessing-clues.mdx"),
  "zh-hans/generations-and-settings": () => import("./knowledge/zh-hans/generations-and-settings.mdx"),
  "zh-hans/forms-and-mega-evolution": () => import("./knowledge/zh-hans/forms-and-mega-evolution.mdx"),
  "zh-hant/late-bloomers-pokemon": () => import("./knowledge/zh-hant/late-bloomers-pokemon.mdx"),
  "zh-hant/guessing-clues": () => import("./knowledge/zh-hant/guessing-clues.mdx"),
  "zh-hant/generations-and-settings": () => import("./knowledge/zh-hant/generations-and-settings.mdx"),
  "zh-hant/forms-and-mega-evolution": () => import("./knowledge/zh-hant/forms-and-mega-evolution.mdx"),
};

export default knowledgeLoaders;
